### ISSUE TITLE
Error Element type is invalid

### ISSUE THREAD

**Issue by EnettyTech** [WrathChaos/react-native-gradient-header#1]
I import lib to my project but when build then has error:
`Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.`

**Comment by kuraydev** [comment]
Digging for it :) Thank you for the report.

**Comment by kuraydev** [comment]
Hello again @bachlongkocanh,
Have you ever tried "example" file? I've tried the latest release and it is working. I could not reproduce this issue. 
Are you using this library on an Expo project? If not, can you share a reproducible example with me?

**Comment by EnettyTech** [comment]
Hi @WrathChaos. I'm init new project and have same error.
My github project: [https://github.com/bachlongkocanh/Gradient-header](https://github.com/bachlongkocanh/Gradient-header).

**Comment by EnettyTech** [comment]
Yeah. I found solution for this issues. You need update README.md.
Change `import { GradientHeader } from "react-native-gradient-header";`
to `import GradientHeader from "react-native-gradient-header";`

**Comment by kuraydev** [comment]
Ah so sorry for this mistake. In the example, it is using the correct way. Thank you @bachlongkocanh  :)

**Comment by kuraydev** [comment]
@bachlongkocanh  Also removed unrelated peer dependencies. 

## [Release 0.0.16](https://github.com/WrathChaos/react-native-gradient-header/releases/tag/0.0.16)
